### ISSUE TITLE
Example and documentation how to log from affiliated packages

### ISSUE THREAD

**Issue by cdeil** [astropy/package-template#134]
This discussion started with @eteq at https://github.com/gammapy/gammapy/issues/315#issuecomment-127771849 ... I think this issue is a better place.

@eteq, @embray The questions I have are:
1. What is the recommended way to emit log messages from Astropy-affiliated packages?
2. What is the recommended way to configure the logger for command line tools in Astropy-affiliated packages?

I read through the [Astropy logging system docs page](http://astropy.readthedocs.org/en/latest/logging.html), but it's not clear to me if that is advice only for Astropy and if affiliated packages should do something different (e.g. make a child logger). Also it doesn't mention how to set up the logger from command line tools, and the example I looked at [hub_script](https://github.com/astropy/astropy/blob/5d419bbc438701e3bc99819ae5a36d9de95f5d41/astropy/vo/samp/hub_script.py#L189) is pretty complex.

So in Gammapy we started with the simplest approach ... use `import logging; logging.info('...')` in the package, i.e. use the root logger and from the command line try to configure the root logger with `logging.basicConfig`: [example](https://github.com/gammapy/gammapy/blob/1827d167da851bb5848ff13066f183619dbf8367/gammapy/scripts/find_obs.py#L117)
This doesn't work, the `logging.basicConfig` has no effect for reasons I still don't understand. If I move the `logging.basicConfig` call to the top of the files after the imports it works!? The [`logging.basicConfig` docs](https://docs.python.org/2/library/logging.html#logging.basicConfig) say "This function does nothing if the root logger already has handlers configured for it.". Who / why as configured handlers for the root logger in this case?

So I guess using the `root` logger is brittle and not a good idea?
@eteq suggested to try this in https://github.com/gammapy/gammapy/issues/315#issuecomment-127779861 but I don't think it works (or I don't know how to use it properly):

``` python
>>> import astropy
>>> log = astropy.log.getChild('gammapy')
>>> log.info('hi')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py", line 1274, in info
    self._log(INFO, msg, args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py", line 1409, in _log
    self.handle(record)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py", line 1419, in handle
    self.callHandlers(record)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py", line 1481, in callHandlers
    hdlr.handle(record)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py", line 853, in handle
    self.emit(record)
  File "/Users/deil/Library/Python/3.4/lib/python/site-packages/astropy-1.1.dev13137-py3.4-macosx-10.10-x86_64.egg/astropy/logger.py", line 604, in emit
    record.message = "{0} [{1:s}]".format(record.msg, record.origin)
AttributeError: 'LogRecord' object has no attribute 'origin'
```

Help!?

**Comment by embray** [comment]
Hmm, good questions all.  Proper use of the logging module is in my wheelhouse so I'll look into this and get back to you.  This is one of those kinds of things (along with discussions we've had in the past about data file downloads) that I'd love to have better user documentation for regarding best-practices, etc.

**Comment by embray** [comment]
> Who / why as configured handlers for the root logger in this case?

I don't know.  Astropy doesn't do anything with the root logger.  You could check by having it `print(logging.getLogger().handlers)` and so on.  It could be that some other code is calling `logging.basicConfig` first.

A more common pattering for using the logging module, rather than using the root logger directly, is to create a logger for each module like:
```python
import logging

log = logging.getLogger(__name__)

log.info('Logging messages from the {0} module'.format(__name__))
```
and so on.  The use of `__name__` is no required, you can use any name you want.  But this makes it automatically use the name of the module being logged from, which is convenient for debugging purposes (the logger class still records the filename and line number that all log messages come from, regardless of what you name the logger instance itself).

If you really want those things you can still use `astropy.log` directly.  As I said, it will still report the log messages as coming from gammapy.  But I can also see a case for being able to use the AstropyLogger without making it a child logger of the log for astropy itself (i.e. an equivalent of `logging.getLogger())`.

Before I ramble on any longer though maybe you should explain what it is you actually want in terms of logging.  Part of the reason that there's no one answer to your question is that there are lots of different applications and use cases for logging and there's no one right way to do lots of things (other than, at some level, using the `logging` module since it already does most of what you need, once you know what you need).

**Comment by embray** [comment]
If you want a decent example of writing a console script that uses the logging module, have a look at:
https://github.com/astropy/astropy/blob/master/astropy/io/fits/scripts/fitsdiff.py
There's still a fair amount of boilerplate involved there (but that's typical since, as I said, there's no one right way depending on the application).

That said, if we *can* come up with a set of "best practices" that astropy packages can use for console scripts I think that would be nice.  Both for logging and command-line parsing.  If we can do that we can bundle up most of that boilerplate.  I think that should be raised on the main issue tracker though, and maybe as an APE.

**Comment by embray** [comment]
(Also, I'll add, I like the fitsdiff example because it demonstrates good practices with respect to separating out application code (option handling, log setup, I/O handling, etc.) from the actual algorithm logic.  All the real code is buried away in the `FITSDiff` class.  The rest is just a wrapper around it to deal with all user-interface ugliness.)

**Comment by cdeil** [comment]
@embray – Thank you for the comments!

I think what we need in terms of logging is pretty basic. Command line tools with an option `--loglevel` to set the loglevel and a second option to log to a file instead or in addition to stdout (is there a standard way how to handle this and / or to file?). Color would be nice, so that warnings and errors are orange and red if logged to a terminal that supports color (as far as I know color is not easily possible in log files?). 

That's it.
(We have one function that uses multiprocessing at the moment, but I don't think it emits log messages, so no worries about parallel logging.)

Is it now possible to give a more specific recommendation?
E.g. is it better to use the root logger, or have one gammapy logger, or one logger per module in gammapy, or re-use an Astropy logger?
I'll read a bit more about Python logging and play with it today, before I start coding up a solution for Gammapy.

**Comment by cdeil** [comment]
I've gone ahead and implemented a simple solution for Gammapy ... @embray if you could have a look and give feedback, that would be very helpful!

I think this way of emitting log messages is OK?
https://github.com/gammapy/gammapy/pull/318/files#diff-00ab472a96028e9c3bcd77657d6c3701R647

From command line tools, I'm using the root logger and configuring it in a utility function:
https://github.com/gammapy/gammapy/pull/318/files#diff-00ab472a96028e9c3bcd77657d6c3701R679

The command line tool user can only set the log level, not the format.
I don't know how to color the log, yet.

Is this OK, or is using the root logger a bad idea?
(I want something simple, and I want to format all log messages the same, whether they come from Astropy or Gammapy or any other package.)

**Comment by astrofrog** [comment]
I'm jumping into this conversation a bit late, but why not re-use the ``AstropyLogger`` class from Astropy and inherit from this, since it already does a lot of nice things like finding the origin of warnings/info messages, dealing with the coloring, etc?

(note, I'm not saying to use the *instance* of the astropy logger, but the class)

**Comment by cdeil** [comment]
@astrofrog Is there a working example of how to use `AstropyLogger`? Should I sub-class ` GammapyLogger` in Gammapy and then instantiate it in each command line script? How can I configure it so that all log messages (from Astropy or Gammapy or other packages) are formatted the same way (ideally in color)?

**Comment by pllim** [comment]
https://github.com/astropy/package-template#deprecation-warning

Also astropy.log is actually meant for internal use within astropy only. We had updated its doc to say as much since then.
