### ISSUE TITLE
Include changes from astropy/astropy#4356

### ISSUE THREAD

**Issue by eteq** [astropy/package-template#145]
astropy/astropy#4356 changes the `astropy/__init__.py` with some minor enhancements, and those should probably be ported over here at some point

**Comment by embray** [comment]
:+1:

**Comment by embray** [comment]
On a related note, we really maybe ought to reverse the flow of updates we currently make from astropy into the package template, and actually switch things around so that astropy itself is based on the package-template.  That'll probably take some tweaking at both ends but is probably the best idea long term...

**Comment by bsipocz** [comment]
@eteq - These changes should go into ``_astropy_init.py``, don't they?

**Comment by pllim** [comment]
If we go the route of astropy/astropy-APEs#52 , then this is no longer relevant.

**Comment by pllim** [comment]
Irrelevant due to #438
