### ISSUE TITLE
package-template introduces a dependency on astropy

### ISSUE THREAD

**Issue by andamian** [astropy/package-template#223]
There is a dependency on astropy when using the package-template:

"File "mypackage/__init__.py", line 10, in 
from ._astropy_init import *
File "mypackage/_astropy_init.py", line 118, in 
from astropy.config.configuration import (
ImportError: No module named astropy.config.configuration

In my project, I've patched it by moving the import from line 118 down to just before it's being used (line 130) and that work. Can this make it upstream into the main repo?

Also, while at it, can the test target be re-factored to not depend on astropy (I'm just assuming it's a problem with package-template but it could be somewhere else):

"python setup.py test
Downloading 'astropy-helpers'; run setup.py with the --offline option to force offline installation.
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: The 'test' command requires the astropy package to be installed and importable.
"

PS: I realize that I am an outlier because my projects do not depend (yet) on astropy or numpy.

**Comment by bsipocz** [comment]
This may be partly be addressed by the cookiecutter and when/if we factor out the test runner from core, otherwise it probably affects only a very small number of non affiliated packages. 

This I probably won't have any time to work on this, as would classify it as a low-priority issue, but needless to say that anyone wants to work on it is more than welcome to do so.

**Comment by pllim** [comment]
https://github.com/astropy/package-template#deprecation-warning
