### ISSUE TITLE
Drop Python 2 support

### ISSUE THREAD

**Issue by pllim** [astropy/package-template#264]
Along with astropy/astropy#6556 and astropy/astropy-helpers#337

The reasoning is that if someone is using this template to create a new package at this point, it would probably depend on Astropy 3, which does not support Python 2 anyway.

**Comment by bsipocz** [comment]
Million 👍 to this, as I see this change is to be that we don't actively encourage usage of python2 after astropy3.0. That said, anyone wanting to still use it can add things back to their package infrastructure.

**Comment by bsipocz** [comment]
(That said, it's still an issue how to help current packages to have a smooth transition.)

**Comment by astrofrog** [comment]
I think this should be a cookiecutter option rather than completely removing support.

**Comment by eteq** [comment]
Re-visiting this topic given that events have evolved in the meantime (channeling some in-peson discussion with @pllim and @bsipocz). Since we are in the final year of py2, perhaps it's the time to truly drop support if we do #384, we could tag a release now as the final one that supports py2 (although it should be the SHA immediately prior to #382), and tag that as 2.0, and then tag the "post py2-removal" to 3.0, and then continue on from there. We just have to be sure to include something in the README that makes this situation clear for those who are using the template.

**Comment by pllim** [comment]
I think this was addressed by #385 and we can close it?

**Comment by bsipocz** [comment]
Yes! Thanks @pllim for triaging all these issues.
