### ISSUE TITLE
`package-template` is hard coded as header of the page

### ISSUE THREAD

**Issue by simontorres** [astropy/package-template#331]
The combination logo + package-template seems to be hard coded in the template. In my opinion it should take the name of the project by default. For instance I just found that specutils still have package-template on it.
![package-template](https://user-images.githubusercontent.com/3878895/39725424-26aae900-5222-11e8-9f1d-9279c4f5179d.png)

**Comment by simontorres** [comment]
Forgot to mention that this might be related to #191

**Comment by bsipocz** [comment]
@simontorres - Yes, somewhat related, but this now need to be done within the cookiecutter templating.

**Comment by eteq** [comment]
@simontorres - to clarify, it is *not* hard-coded - you can see astropy/specutils#200 for an example of how to change it to a different name... But your point is well taken that this isn't in the conf.py 

That said, I think the fix fir this issue is actually "add the section to the `conf.py` template". I'll try to make a PR to fix this shortly.

**Comment by eteq** [comment]
Fixed in  #336
