### ISSUE TITLE
add circleci build for documentation with artefacts?

### ISSUE THREAD

**Issue by Cadair** [astropy/package-template#366]
Should we add an optional CircleCI set of configs?

**Comment by bsipocz** [comment]
I'm not that sure about this, circleCI's UX is still far from ideal and failing in cryptic ways (e.g. it stops testing when no one is subscribed for a given repo, and it wasn't that we unsubscribed, it removed us for some weird reasons. So all these can be especially problematic for small packages with just one maintainer, etc.)

But otherwise, sure, having the configs around as templates can be useful, all I'm saying it shouldn't be the default CI we suggest for any projects.

**Comment by Cadair** [comment]
> all I'm saying it shouldn't be the default CI we suggest for any projects.

I agree, but having the configs in the template would be useful if people wanted to use them. The artefact handling on CircleCI is just light years ahead of Travis.

**Comment by pllim** [comment]
RTD has auto PR builder now.
